apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  template:
    spec:
      containers:
      - name: mariadb
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
