apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  template:
    spec:
      containers:
      - name: cloudflared
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
