apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  project: default
  destination:
    namespace: cloudflared
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/chapst1k/k3_homelab.git
    targetRevision: main
    path: gitops-apps/cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
