apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      volumes:
      - name: ssh-key
        $patch: delete
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - name: ssh-key
          $patch: delete
