{
 "title": "Catalyst 9300 gRPC Model Driven Telemetry",
 "description": "Cisco IOS XE and the Catalyst 9300 switch using the gRPC Dial-Out Model-Driven Telemetry interface to provide basic health and interface monitoring capabilities",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Last Boot",
   "type": "singlestat",
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openconfig-system:system/state",
     "select": [
      [
       { "params": [ "boot_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openconfig-platform:components/component/fan/state",
     "select": [
      [
       { "params": [ "openconfig_platform_fan:speed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openconfig-platform:components/component/state/temperature",
     "select": [
      [
       { "params": [ "instant" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization",
     "select": [
      [
       { "params": [ "five_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Five Seconds" ], "type": "alias" }
      ],
      [
       { "params": [ "one_minute" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "One Minute" ], "type": "alias" }
      ],
      [
       { "params": [ "five_minutes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Five Minutes" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Supply",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]] $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openconfig-platform:components/component/power-supply/state",
     "select": [
      [
       {
        "params": [
         "openconfig_platform_psu:output_power"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Output Power" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "openconfig_platform_psu:capacity"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Capacity" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openconfig-interfaces:interfaces/interface/state/counters",
     "select": [
      [
       { "params": [ "in_octets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Ingress Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "out_octets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Egress Bytes" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Egress Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openconfig-interfaces:interfaces/interface/state/counters",
     "select": [
      [
       { "params": [ "out_octets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ingress Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openconfig-interfaces:interfaces/interface/state/counters",
     "select": [
      [
       { "params": [ "in_octets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  }
 ]
}