apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: technitium-dns
  namespace: dns
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: technitium-dns
  namespaceSelector:
    matchNames:
      - dns
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
