apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
spec:
  template:
    spec:
      containers:
      - name: ghost
        env:
        - name: GHOST_HOST
          value: zmartin.me
