apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
spec:
  template:
    spec:
      containers:
        - name: ghost
          env:
            - name: GHOST_HOST
              value: zmartin.me

            - name: mail__transport
              value: SMTP

            - name: mail__options__host
              value: mail.smtp2go.com

            - name: mail__options__port
              value: "587"

            - name: mail__options__secure
              value: "false"

            - name: mail__options__auth__user
              valueFrom:
                secretKeyRef:
                  name: ghost-smtp
                  key: username

            - name: mail__options__auth__pass
              valueFrom:
                secretKeyRef:
                  name: ghost-smtp
                  key: password

            - name: mail__from
              value: '"Ghost Admin" <no-reply@zmartin.me>'
