---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-secret
  namespace: default
spec:
  encryptedData:
    mariadb-password: AgBrxxSqDj6UN6osndq7MAs7sqOyhVWme6OOaEj88JqsjfzdfjmtWo5OVwsFUE6uDeyS7ItqTtfJuJGKjzoxErbzJkTkzxcbfXOQb6CTb34mN0lLJ9oJGyG626rH9bEVuWXGAb7pXl/BIeLOakJbhTUHFVb9vHXuRwTOrqtg6RdnjkvCC6rFlJmO4l2qvCRZ4PZ/XlPlwCjlgvh6aqItRsyNaIeSp+6M079jYtNYmWpw1UblCr7vyD79qoSwosW3YnANllAgKcLIX1T0QpzlsTeatTbRK2byfkYhjZKd1/UkpTaHu6+j9cWS0g2ikw3WdlY0chQa6xv36NGX8V8gEITEcgDambMCrRjvj0JS6Ula1Gv+O2wPGTvD2lVpS3FNqE4RyIqPThwlLYgM/Rl1o7c7OyDi4djlNhw7ykwke8l/lH7w6icPxfC8KPUQPWNpTMMV4PWTnCoXVkeXmQ2S43w1GUEhAteClHaiLYkT9OxhtiqkXhldOmrjmmcTwZlnVTNkhVNEdDYne0XNJp4Ind+jE9nIV+a7fFKbeLTV/+bl5ilF0C+4yyLADa6hZYBMkTfseP3BH9RBVF3l41e/igu8h+DpoVqS/xiZ1NGLOrpjh0um/nbl/C4d4Ahkz5eLOqTXzX/dA+AUG8jowkNipQMT41xLW2lakdQCi0AbuEXopYsjGvaUnyvyt45umQNv9AHWM1GMuskya7u22KpwLWndAPv2ndDpRoxCUAImqx5wqA==
    mariadb-root-password: AgDOlc2auJdMI8K6yV77FqpCdjjGFrukY8MZmNa/f2F0MOj6gmjw1ou845xoHD8lPyTguy79JmkbMpD2AJPaIZkhEWtb0n4/bYHGeSr2gjKtFxyFQ3fkZOv3nmsDS64xvoj5sW85E8p81un6FcfM2SqAHydBEpPUpT3u7c0MSjrWQjCltnLgoJn6PiXPPKbJ0GEMkfiimcnG8XMaeAoIGGDsgmgK82fsI/bQM1MFwQ6M5A2zCFmXFWRtLk3tz579I1upSUE2vMNLBrxPvgaYVeqspQ0Z8rL2AeNr4/Wk0oy866uKQhkAkQZjOtWXsJ9IuVFgj9HZJe4iNbuP0tPowH+8Qn3cmZZurU+VCfbJfOkfK0nO34ZbG1pb+a2n7pdU0fuDOOatEK9Vda/75E46RGZ37cp5OxaG3sGd7XPvPN3iWrgOScstTzpK3NI2ssyPD6n99T7rFqgJd+HrFi6qaOBRGPP532yIL6ZY019/jZU/FrWu/g8YMevxFm11iDH/PvtX9MfWaW2+yLNKwApICBvHRquyrqdm0XT7Cl1G1xRFrqihgWL1+eZu4AhsauOM3Fb+fZVyeomtF0KTak20MIB5X9a3SOYYwDtPlpN6CSn4TnyG0oAW0k4eD1CXWwRWPQ+EifUnbEoK+wv4Cc/weMlYd+0DniZharji6dFeAGdkRcqY+VwtmEBKe5oraIyLx9JC9X/U5lLM6gBEVrBCBXOFh1/zdl22a6MTCuI90O+kkA==
  template:
    metadata:
      name: mariadb-secret
      namespace: default
    type: Opaque
