apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: cloudflare
type: Opaque
stringData:
  token: "ZXlKaElqb2lOVE16WlRCaVpXTXdNVFZrWkdNd016VmlNREptTmpRMlpUQm1OR1EyTjJVaUxDSjBJam9pWlRKaVlUazBPRFF0TnpJeU1TMDBaRFk0TFRnelpXUXRZekl5T1RJNU5XUmhORFEySWl3aWN5STZJbGxxYXpSUFZFMDBXa2RWZEU1SFVYaE9VekF3VG1wak0weFhSbWxQUkZGMFQwUk9hRmt5UlhoTk1rVjNXbXBXYlNKOQ=="
